"""add apartment max_guests and blocked_dates table

Revision ID: 330aeb83e864
Revises: 68eb3186bce2
Create Date: 2026-07-24 14:54:30.013971

Autogenerate doesn't detect CHECK constraints added to an already-existing
table (same class of limitation as the EXCLUDE-constraint note in
7c4446bc8a36), so ck_apartments_max_guests_positive is added by hand below.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '330aeb83e864'
down_revision: Union[str, None] = '68eb3186bce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_dates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('apartment_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('apartment_id'), '='), (sa.text("daterange(start_date, end_date, '[]')"), '&&'), using='gist', name='ex_blocked_dates_no_overlap'),
    sa.CheckConstraint('end_date >= start_date', name='ck_blocked_dates_end_after_start'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_dates_apartment_id'), 'blocked_dates', ['apartment_id'], unique=False)
    op.add_column('apartments', sa.Column('max_guests', sa.Integer(), server_default=sa.text('4'), nullable=False))
    op.create_check_constraint(
        'ck_apartments_max_guests_positive', 'apartments', 'max_guests > 0'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_apartments_max_guests_positive', 'apartments', type_='check')
    op.drop_column('apartments', 'max_guests')
    op.drop_index(op.f('ix_blocked_dates_apartment_id'), table_name='blocked_dates')
    op.drop_table('blocked_dates')
    # ### end Alembic commands ###
