"""add ical_sources table and blocked_dates ical columns

Revision ID: 3610fd63e346
Revises: 8b1d751820ac
Create Date: 2026-08-24 20:26:49.148383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3610fd63e346'
down_revision: Union[str, None] = '8b1d751820ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ical_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('apartment_id', sa.UUID(), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('ical_url', sa.String(length=1000), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ical_sources_apartment_id'), 'ical_sources', ['apartment_id'], unique=False)
    op.add_column('blocked_dates', sa.Column('ical_source_id', sa.UUID(), nullable=True))
    op.add_column('blocked_dates', sa.Column('external_uid', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_blocked_dates_ical_source_id'), 'blocked_dates', ['ical_source_id'], unique=False)
    op.create_index('ix_blocked_dates_ical_source_id_external_uid', 'blocked_dates', ['ical_source_id', 'external_uid'], unique=True, postgresql_where=sa.text('ical_source_id IS NOT NULL'))
    op.create_foreign_key(
        'blocked_dates_ical_source_id_fkey',
        'blocked_dates', 'ical_sources', ['ical_source_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blocked_dates_ical_source_id_fkey', 'blocked_dates', type_='foreignkey')
    op.drop_index('ix_blocked_dates_ical_source_id_external_uid', table_name='blocked_dates', postgresql_where=sa.text('ical_source_id IS NOT NULL'))
    op.drop_index(op.f('ix_blocked_dates_ical_source_id'), table_name='blocked_dates')
    op.drop_column('blocked_dates', 'external_uid')
    op.drop_column('blocked_dates', 'ical_source_id')
    op.drop_index(op.f('ix_ical_sources_apartment_id'), table_name='ical_sources')
    op.drop_table('ical_sources')
    # ### end Alembic commands ###
