"""add rate_rules table

Revision ID: 68eb3186bce2
Revises: c6a72ff86519
Create Date: 2026-07-22 11:21:39.620645

Unlike the bookings EXCLUDE constraint (see 7c4446bc8a36), autogenerate
picked this one up fine — it only misses EXCLUDE constraints added to an
already-existing table, not ones present on a brand new table. btree_gist
(needed for the GiST index over the plain-equality apartment_id column) was
already enabled by 7c4446bc8a36, so this migration doesn't repeat it.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68eb3186bce2'
down_revision: Union[str, None] = 'c6a72ff86519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('apartment_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_stay', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('apartment_id'), '='), (sa.text("daterange(start_date, end_date, '[]')"), '&&'), using='gist', name='ex_rate_rules_no_overlap'),
    sa.CheckConstraint('end_date >= start_date', name='ck_rate_rules_end_after_start'),
    sa.CheckConstraint('min_stay > 0', name='ck_rate_rules_min_stay_positive'),
    sa.CheckConstraint('price_per_night > 0', name='ck_rate_rules_price_per_night_positive'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_rules_apartment_id'), 'rate_rules', ['apartment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_rules_apartment_id'), table_name='rate_rules')
    op.drop_table('rate_rules')
    # ### end Alembic commands ###
