"""add bookings table

Revision ID: 71df480aa928
Revises: caa9d7a24502
Create Date: 2026-07-17 11:48:57.204207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71df480aa928'
down_revision: Union[str, None] = 'caa9d7a24502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('apartment_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('confirmation_code', sa.String(length=12), nullable=False),
    sa.Column('guest_full_name', sa.String(length=255), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=False),
    sa.Column('guest_phone', sa.String(length=50), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'completed', name='bookingstatus', native_enum=False, create_constraint=True, length=20), server_default='pending', nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('check_out_date > check_in_date', name='ck_bookings_check_out_after_check_in'),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_code')
    )
    op.create_index(op.f('ix_bookings_apartment_id'), 'bookings', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_bookings_owner_id'), 'bookings', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_owner_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_apartment_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
