"""Add amenities to apartments

Revision ID: 8b1d751820ac
Revises: f36b4e995efe
Create Date: 2026-08-14 16:15:35.847007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b1d751820ac'
down_revision: Union[str, None] = 'f36b4e995efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('amenities', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('apartments', sa.Column('amenities_other', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'amenities_other')
    op.drop_column('apartments', 'amenities')
    # ### end Alembic commands ###
