"""add users table and owner user_id link

Revision ID: 9597099776e8
Revises: 2e8759fc2a94
Create Date: 2026-07-20 18:12:53.421703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9597099776e8'
down_revision: Union[str, None] = '2e8759fc2a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'owner', name='userrole', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('owners', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('owners_user_id_key', 'owners', ['user_id'])
    op.create_foreign_key(
        'owners_user_id_fkey', 'owners', 'users', ['user_id'], ['id'], ondelete='RESTRICT'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('owners_user_id_fkey', 'owners', type_='foreignkey')
    op.drop_constraint('owners_user_id_key', 'owners', type_='unique')
    op.drop_column('owners', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
