"""add apartment check_in_instructions and booking checkin_reminder_sent_at

Revision ID: a5d876f184e3
Revises: 3610fd63e346
Create Date: 2026-09-02 13:29:48.930417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d876f184e3'
down_revision: Union[str, None] = '3610fd63e346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('check_in_instructions', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('checkin_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'checkin_reminder_sent_at')
    op.drop_column('apartments', 'check_in_instructions')
    # ### end Alembic commands ###
