"""Add apartment_photos table

Revision ID: f36b4e995efe
Revises: 7811de59bca8
Create Date: 2026-08-10 20:43:46.702327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36b4e995efe'
down_revision: Union[str, None] = '7811de59bca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment_photos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('apartment_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apartment_photos_apartment_id'), 'apartment_photos', ['apartment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apartment_photos_apartment_id'), table_name='apartment_photos')
    op.drop_table('apartment_photos')
    # ### end Alembic commands ###
